# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16NmGMWf_6p3Ep4GT7Q5SPCNKuemur5YC
"""

def real_madrid(belgi):
 if belgi=="7":
  return "Vinicius Júnior"
 elif belgi=="10":
  return "Luka Modrić"
 elif belgi == "1":
  return "Thibaut Courtois"
 elif belgi=="8":
  return belgi=="Federico Valverde"
 elif belgi == "14":
  return belgi=="Aurélien Tchouaméni"
 elif belgi=="6":
  return "Eduardo Camavinga"
 elif belgi == "5":
  return "Jude Bellingham"
 elif belgi=="11":
  return belgi=="Rodrygo"
 elif belgi == "9":
  return belgi=="Kylian Mbappé"
 elif belgi == "23":
  return "Ferland Mendy"
 elif belgi=="4":
  return "David Alaba"
 elif belgi=="22":
  return belgi=="Antonio Rüdiger"
 elif belgi == "2":
  return belgi=="Dani Carvajal"
 elif belgi == "6":
  return "Nacho Fernández"
 elif belgi=="25":
  return "Eduardo Camavinga"
 elif belgi=="24":
  return belgi=="Mariano Díaz"
 elif belgi == "8":
  return belgi=="Toni Kroos"
 elif belgi == "17":
  return "Lucas Vázquez"
 elif belgi=="20":
  return "Fran García"
 else:
  return "bu raqamda o'yinchi yo'q"
belgi=input ("fudbolchi raqamini kiriting\n>>>")
natija=real_madrid(belgi)
print(natija)